# Traduction anglais -> francais pour les 73 indicateurs TradingEconomics Maroc
INDICATEURS_FR = {
'Balance of Trade': 'Balance commerciale',
'Banks Balance Sheet': 'Bilan des banques',
'CPI Clothing': 'IPC Habillement',
'CPI Education': 'IPC Education',
'CPI Food': 'IPC Alimentation',
'CPI Housing Utilities': 'IPC Logement et charges',
'CPI Recreation and Culture': 'IPC Loisirs et culture',
'CPI Restaurants and Hotels': 'IPC Restaurants et hotels',
'CPI Transportation': 'IPC Transports',
'Capital Flows': 'Flux de capitaux',
'Central Bank Balance Sheet': 'Bilan de la banque centrale',
'Changes in Inventories': 'Variation des stocks',
'Consumer Confidence': 'Confiance des consommateurs',
'Consumer Price Index CPI': 'Indice des prix a la consommation',
'Consumer Spending': 'Depenses de consommation',
'Core Inflation Rate': 'Inflation sous-jacente',
'Corporate Tax Rate': 'Impot sur les societes',
'Corruption Index': 'Indice de corruption',
'Corruption Rank': 'Rang corruption',
'Credit Rating': 'Note de credit',
'Currency': 'Devise (MAD/USD)',
'Current Account': 'Compte courant',
'Current Account to GDP': 'Compte courant / PIB',
'Deposit Interest Rate': "Taux d'interet des depots",
'Employed Persons': 'Personnes en emploi',
'Employment Rate': "Taux d'emploi",
'Exports': 'Exportations',
'Food Inflation': 'Inflation alimentaire',
'Foreign Direct Investment': 'Investissements directs etrangers',
'Foreign Exchange Reserves': 'Reserves de change',
'Full Year GDP Growth': 'Croissance annuelle du PIB',
'GDP': 'PIB',
'GDP Annual Growth Rate': 'Croissance du PIB',
'GDP Constant Prices': 'PIB a prix constants',
'GDP from Agriculture': 'PIB Agriculture',
'GDP from Construction': 'PIB Construction',
'GDP from Manufacturing': 'PIB Industrie manufacturiere',
'GDP from Mining': 'PIB Mines',
'GDP from Public Administration': 'PIB Administration publique',
'GDP from Services': 'PIB Services',
'GDP from Transport': 'PIB Transports',
'GDP from Utilities': 'PIB Energie et eau',
'GDP per Capita': 'PIB par habitant',
'Gold Reserves': "Reserves d'or",
'Government Budget': 'Budget public',
'Government Debt to GDP': 'Dette publique / PIB',
'Government Spending': 'Depenses publiques',
'Gross Fixed Capital Formation': 'Formation brute de capital fixe',
'Imports': 'Importations',
'Industrial Production': 'Production industrielle',
'Inflation Rate': 'Inflation',
'Inflation Rate MoM': 'Inflation mensuelle',
'Interest Rate': "Taux d'interet",
'Military Expenditure': 'Depenses militaires',
'Minimum Wages': 'Salaire minimum',
'Mining Production': 'Production miniere',
'Money Supply M1': 'Masse monetaire M1',
'Money Supply M2': 'Masse monetaire M2',
'Money Supply M3': 'Masse monetaire M3',
'Personal Income Tax Rate': 'Impot sur le revenu',
'Personal Savings': 'Epargne des menages',
'Population': 'Population',
'Producer Prices': 'Prix a la production',
'Sales Tax Rate': 'TVA',
'Social Security Rate': 'Charges sociales',
'Social Security Rate For Companies': 'Charges patronales',
'Social Security Rate For Employees': 'Charges salariales',
'Stock Market': 'Bourse',
'Terrorism Index': 'Indice de terrorisme',
'Tourist Arrivals': 'Arrivees touristiques',
'Unemployed Persons': 'Chomeurs',
'Unemployment Rate': 'Chomage',
'Youth Unemployment Rate': 'Chomage des jeunes',
}

UNITES_FR = {
'percent': '%',
'percent of GDP': '% du PIB',
'MAD Million': 'millions MAD',
'MAD/Month': 'MAD/mois',
'Million': 'millions',
'Points': 'points',
'points': 'points',
'Thousand': 'milliers',
'Tonnes': 'tonnes',
'USD': 'USD',
'USD Billion': 'milliards USD',
'USD Million': 'millions USD',
}

def traduire_indicateur(nom_en: str) -> str:
    return INDICATEURS_FR.get(nom_en, nom_en)

def traduire_unite(u: str) -> str:
    if not isinstance(u, str):
        return u
    return UNITES_FR.get(u, UNITES_FR.get(u.strip(), u))
